spring:
    application:
        name: dispatcher

---
spring:
    profiles: test
    datasource:
        url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver: org.h2.Driver

#    datasource:
#        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost/test
#server:
#    port: 9000